import { Link } from 'react-router-dom'
import { ArrowRight, Check, ShieldCheck, Sparkles } from 'lucide-react'
import SearchPanel from '../components/SearchPanel'
import PropertyCard from '../components/PropertyCard'
import SectionHeading from '../components/SectionHeading'
import { properties } from '../data/properties'

export default function Home() {
  return <main>
    <section className="relative overflow-hidden bg-brand-50"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 pb-16 pt-12 lg:grid-cols-[0.9fr_1.1fr] lg:px-8 lg:pb-24 lg:pt-20"><div className="relative z-10"><div className="mb-5 inline-flex items-center gap-2 rounded-full bg-white px-3 py-1.5 text-xs font-semibold text-brand-700 shadow-sm"><Sparkles size={14}/> Better places. More flexible living.</div><h1 className="max-w-xl text-5xl font-bold leading-[1.02] tracking-tight text-ink sm:text-6xl lg:text-7xl">Find a home that <span className="text-brand-600">fits your life.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-stone-600 sm:text-lg">Discover thoughtfully furnished homes in great neighbourhoods, ready for the way you live today.</p><div className="mt-8"><SearchPanel/></div></div><div className="relative"><div className="overflow-hidden rounded-[2rem] shadow-2xl"><img src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85" alt="Beautiful modern rental home" className="h-[420px] w-full object-cover sm:h-[520px]"/></div><div className="absolute -bottom-5 -left-3 rounded-2xl bg-white p-4 shadow-xl sm:-left-6"><div className="flex -space-x-2"><img className="h-9 w-9 rounded-full border-2 border-white object-cover" src="https://i.pravatar.cc/80?img=12"/><img className="h-9 w-9 rounded-full border-2 border-white object-cover" src="https://i.pravatar.cc/80?img=32"/><img className="h-9 w-9 rounded-full border-2 border-white object-cover" src="https://i.pravatar.cc/80?img=44"/></div><p className="mt-2 text-xs font-semibold">Loved by 10,000+ renters</p></div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><SectionHeading eyebrow="Featured homes" title="Places worth coming home to" description="Handpicked rentals with the details that make everyday living feel effortless." action={<Link to="/properties" className="flex items-center gap-2 text-sm font-bold text-brand-600">View all homes <ArrowRight size={16}/></Link>}/><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{properties.filter(p => p.featured).slice(0, 6).map(p => <PropertyCard key={p.id} property={p}/>)}</div></section>
    <section className="bg-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><SectionHeading eyebrow="Why Flex Living" title="Renting, without the usual friction" description="Everything you need to feel at home, from search to move-in."/><div className="grid gap-5 md:grid-cols-3"><div className="rounded-2xl bg-brand-50 p-7"><ShieldCheck className="text-brand-600"/><h3 className="mt-5 text-xl font-bold">Trusted homes</h3><p className="mt-2 text-sm leading-6 text-stone-500">Quality-checked properties and transparent listings, so you can book with confidence.</p></div><div className="rounded-2xl bg-stone-50 p-7"><Check className="text-brand-600"/><h3 className="mt-5 text-xl font-bold">Ready to live</h3><p className="mt-2 text-sm leading-6 text-stone-500">Furnished spaces, practical amenities and flexible options designed around real life.</p></div><div className="rounded-2xl bg-brand-50 p-7"><Sparkles className="text-brand-600"/><h3 className="mt-5 text-xl font-bold">Made simple</h3><p className="mt-2 text-sm leading-6 text-stone-500">Search, compare and request a stay from one clear, modern rental experience.</p></div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="overflow-hidden rounded-[2rem] bg-brand-700 px-6 py-12 text-center text-white sm:px-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-100">Your next chapter</p><h2 className="mx-auto mt-3 max-w-2xl text-3xl font-bold sm:text-4xl">A better rental experience starts here.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-white/70">Tell us where you want to live and we'll help you find a place that feels right.</p><Link to="/properties" className="mt-7 inline-flex rounded-full bg-white px-6 py-3 text-sm font-bold text-brand-700">Explore homes</Link></div></section>
  </main>
}
