import { Heart, MapPin, Star, ArrowUpRight, BedDouble } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useFavorites } from '../contexts/FavoritesContext'

export default function PropertyCard({ property }) {
  const { isFavorite, toggleFavorite } = useFavorites()
  const favorite = isFavorite(property.id)
  return <article className="group overflow-hidden rounded-2xl border border-stone-200 bg-white transition duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-stone-900/10"><div className="relative aspect-[4/3] overflow-hidden"><img src={property.image} alt={property.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute left-4 top-4 rounded-full bg-white/95 px-3 py-1.5 text-xs font-semibold text-stone-700">{property.type}</div><button onClick={() => toggleFavorite(property.id)} aria-label={favorite ? 'Remove from favorites' : 'Add to favorites'} className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-white/95 text-stone-600 transition hover:text-red-500"><Heart size={18} fill={favorite ? 'currentColor' : 'none'} className={favorite ? 'text-red-500' : ''}/></button></div><div className="p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="text-lg font-bold text-ink">{property.title}</h3><p className="mt-1 flex items-center gap-1.5 text-sm text-stone-500"><MapPin size={14}/>{property.location}</p></div><div className="flex items-center gap-1 text-sm font-semibold"><Star size={15} fill="currentColor" className="text-amber-500"/>{property.rating}</div></div><div className="mt-4 flex items-center gap-4 text-sm text-stone-500"><span className="flex items-center gap-1.5"><BedDouble size={15}/>{property.bedrooms} bed</span><span>·</span><span>{property.reviews} reviews</span></div><div className="mt-5 flex items-center justify-between border-t border-stone-100 pt-4"><p><span className="text-xl font-bold text-ink">£{property.price.toLocaleString()}</span><span className="text-sm text-stone-400"> / month</span></p><Link to={`/properties/${property.id}`} className="flex items-center gap-1 rounded-full bg-brand-50 px-4 py-2 text-sm font-semibold text-brand-700 transition hover:bg-brand-100">View details <ArrowUpRight size={15}/></Link></div></div></article>
}
